

INSERT INTO Estados VALUES ( 'AC', 'Acre')
INSERT INTO Estados VALUES ( 'AL', 'Alagoas')
INSERT INTO Estados VALUES ( 'AM', 'Amazonas')
INSERT INTO Estados VALUES ( 'AP', 'Amapá')
INSERT INTO Estados VALUES ( 'BA', 'Bahia')
INSERT INTO Estados VALUES ( 'CE', 'Ceará')
INSERT INTO Estados VALUES ( 'DF', 'Distrito Federal')
INSERT INTO Estados VALUES ( 'ES', 'Espírito Santo')
INSERT INTO Estados VALUES ( 'GO', 'Goiás')
INSERT INTO Estados VALUES ( 'MA', 'Maranhão')
INSERT INTO Estados VALUES ( 'MG', 'Minas Gerais')
INSERT INTO Estados VALUES ( 'MS', 'Mato Grosso do Sul')
INSERT INTO Estados VALUES ( 'MT', 'Mato Grosso')
INSERT INTO Estados VALUES ( 'PA', 'Pará')
INSERT INTO Estados VALUES ( 'PB', 'Paraíba')
INSERT INTO Estados VALUES ( 'PE', 'Pernambuco')
INSERT INTO Estados VALUES ( 'PI', 'Piauí')
INSERT INTO Estados VALUES ( 'PR', 'Paraná')
INSERT INTO Estados VALUES ( 'RJ', 'Rio de Janeiro')
INSERT INTO Estados VALUES ( 'RN', 'Rio Grande do Norte')
INSERT INTO Estados VALUES ( 'RO', 'Rondônia')
INSERT INTO Estados VALUES ( 'RR', 'Roraima')
INSERT INTO Estados VALUES ( 'RS', 'Rio Grande do Sul')
INSERT INTO Estados VALUES ( 'SC', 'Santa Catarina')
INSERT INTO Estados VALUES ( 'SE', 'Sergipe')
INSERT INTO Estados VALUES ( 'SP', 'São Paulo')
INSERT INTO Estados VALUES ( 'TO', 'Tocantins')

SELECT * FROM tb_estados